### ISSUE TITLE
Mnemosyne broken due to missing library

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/mnemosyne#36]
mnemosyne_1       | Traceback (most recent call last):
mnemosyne_1       |   File "/opt/mnemosyne/runner.py", line 29, in <module>
mnemosyne_1       |     from normalizer.normalizer import Normalizer
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
mnemosyne_1       |     from normalizer.modules import glastopf_files
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
mnemosyne_1       |     import magic
mnemosyne_1       |   File "/usr/local/lib/python3.6/dist-packages/magic.py", line 161, in <module>
mnemosyne_1       |     raise ImportError('failed to find libmagic.  Check your installation')
mnemosyne_1       | ImportError: failed to find libmagic.  Check your installation
mnemosyne_1       | Traceback (most recent call last):
mnemosyne_1       |   File "/opt/mnemosyne/runner.py", line 29, in <module>
mnemosyne_1       |     from normalizer.normalizer import Normalizer
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
mnemosyne_1       |     from normalizer.modules import glastopf_files
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
mnemosyne_1       |     import magic
mnemosyne_1       |   File "/usr/local/lib/python3.6/dist-packages/magic.py", line 161, in <module>
mnemosyne_1       |     raise ImportError('failed to find libmagic.  Check your installation')
mnemosyne_1       | ImportError: failed to find libmagic.  Check your installation
mnemosyne_1       | Traceback (most recent call last):
mnemosyne_1       |   File "/opt/mnemosyne/runner.py", line 29, in <module>
mnemosyne_1       |     from normalizer.normalizer import Normalizer
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/normalizer.py", line 22, in <module>
mnemosyne_1       |     from normalizer.modules import glastopf_files
mnemosyne_1       |   File "/opt/mnemosyne/normalizer/modules/glastopf_files.py", line 20, in <module>
mnemosyne_1       |     import magic
mnemosyne_1       |   File "/usr/local/lib/python3.6/dist-packages/magic.py", line 161, in <module>
mnemosyne_1       |     raise ImportError('failed to find libmagic.  Check your installation')
mnemosyne_1       | ImportError: failed to find libmagic.  Check your installation

**Comment by JesseBowling** [comment]
Fixed with https://github.com/CommunityHoneyNetwork/mnemosyne/commit/b91bf5bf6d67c54723d456a901f532a496a8647d
